"""Tests for the tag-scout skill's caption text extractor.

The extractor is the only part of the skill with real logic: everything else
is prompt text. It lives under .claude/skills/ rather than api/, so it is
loaded here by path.

The SCC fixtures below are hand-encoded EIA-608 byte pairs, not round-tripped
through our own encoder -- a fixture generated by the code under test would
prove nothing.
"""

import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parents[1] / ".claude" / "skills" / "tag-scout" / "scripts" / "captions_to_text.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("captions_to_text", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    # @dataclass resolves annotations via sys.modules[cls.__module__], so the
    # module must be registered before exec_module, not after.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


cts = _load_module()


# ---------------------------------------------------------------------------
# Format detection
# ---------------------------------------------------------------------------


class TestDetectFormat:
    def test_scenarist_header_is_scc(self):
        assert cts.detect_format("Scenarist_SCC V1.0\n\n00:00:01;00\t9420 9420\n") == "scc"

    def test_srt_cue_is_srt(self):
        assert cts.detect_format("1\n00:00:01,000 --> 00:00:03,000\nHello\n") == "srt"

    def test_headerless_scc_detected_by_semicolon_timecode_and_hex(self):
        # Some tools drop the Scenarist header. The drop-frame ';' separator
        # plus tab-delimited hex is still unambiguous.
        assert cts.detect_format("00:00:01;00\t9420 9420 c8e5 ecec\n") == "scc"

    def test_unrecognized_content_raises(self):
        with pytest.raises(ValueError):
            cts.detect_format("just some prose that is neither format")


# ---------------------------------------------------------------------------
# SCC decoding
# ---------------------------------------------------------------------------


class TestDecodeSCC:
    def test_pop_on_caption_decodes_to_text(self):
        # RCL, ENM, PAC(row15), "Hello, world.", EOC -- all control codes
        # doubled as a real encoder emits them.
        scc = (
            "Scenarist_SCC V1.0\n\n"
            "00:00:01;00\t9420 9420 94ae 94ae 9470 9470 "
            "c8e5 ecec ef2c 20f7 ef72 ec64 2e80 942f 942f\n"
        )
        caps = cts.decode_scc(scc)
        assert [c.text for c in caps] == ["Hello, world."]

    def test_parity_bits_are_stripped(self):
        # 0xc8 -> 'H' only if the high parity bit is masked off.
        scc = "Scenarist_SCC V1.0\n\n00:00:01;00\t9420 9420 9470 9470 c8e9 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "Hi"

    def test_doubled_control_codes_do_not_duplicate_text(self):
        scc = "Scenarist_SCC V1.0\n\n" "00:00:01;00\t9420 9420 9470 9470 c1c2 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "AB"

    def test_null_padding_is_ignored(self):
        # 0x80 masks to 0x00 -- filler, not a character.
        scc = "Scenarist_SCC V1.0\n\n00:00:01;00\t9420 9420 9470 9470 c180 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "A"

    def test_basic_set_nonascii_codepoints(self):
        # 0x7D is N-tilde in the 608 basic set, not '}'.
        scc = "Scenarist_SCC V1.0\n\n00:00:01;00\t9420 9420 9470 9470 fdfe 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "Ññ"

    def test_special_north_american_char(self):
        # 0x11 0x37 -> music note.
        scc = "Scenarist_SCC V1.0\n\n00:00:01;00\t9420 9420 9470 9470 91b7 91b7 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "♪"

    def test_extended_char_replaces_preceding_fallback(self):
        # Encoder sends 'U' then the extended code for U-umlaut; the decoder
        # must drop the fallback rather than emit both.
        scc = "Scenarist_SCC V1.0\n\n00:00:01;00\t9420 9420 9470 9470 2055 9224 9224 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "Ü"

    def test_channel_two_control_codes_are_ignored(self):
        # 0x1F-range pairs are CC2; we only decode CC1.
        scc = "Scenarist_SCC V1.0\n\n" "00:00:01;00\t9420 9420 9470 9470 c1c2 1f20 1f20 942f 942f\n"
        assert cts.decode_scc(scc)[0].text == "AB"

    def test_roll_up_flushes_on_carriage_return(self):
        # RU2, PAC, "one", CR, "two", CR
        scc = (
            "Scenarist_SCC V1.0\n\n"
            "00:00:01;00\t9425 9425 9470 9470 ef6e e520 94ad 94ad\n"
            "00:00:03;00\t74f7 ef20 94ad 94ad\n"
        )
        assert [c.text for c in cts.decode_scc(scc)] == ["one", "two"]

    def test_start_timecode_is_captured(self):
        scc = "Scenarist_SCC V1.0\n\n00:00:10;00\t9420 9420 9470 9470 c1 942f 942f\n"
        caps = cts.decode_scc(scc)
        assert caps[0].start_ms == pytest.approx(10_000, abs=50)

    def test_empty_file_yields_no_captions(self):
        assert cts.decode_scc("Scenarist_SCC V1.0\n\n") == []


# ---------------------------------------------------------------------------
# SRT parsing
# ---------------------------------------------------------------------------


class TestParseSRT:
    def test_basic_cues(self):
        srt = "1\n00:00:01,000 --> 00:00:03,000\nHello there\n\n2\n00:00:04,000 --> 00:00:06,000\nSecond cue\n"
        caps = cts.parse_srt(srt)
        assert [c.text for c in caps] == ["Hello there", "Second cue"]
        assert caps[0].start_ms == 1000

    def test_multiline_cue_joins_with_space(self):
        srt = "1\n00:00:01,000 --> 00:00:03,000\nfirst line\nsecond line\n"
        assert cts.parse_srt(srt)[0].text == "first line second line"

    def test_malformed_block_is_skipped_not_fatal(self):
        srt = "1\nnot a timecode\nnonsense\n\n2\n00:00:04,000 --> 00:00:06,000\nGood cue\n"
        assert [c.text for c in cts.parse_srt(srt)] == ["Good cue"]


# ---------------------------------------------------------------------------
# Rolling-window de-duplication
#
# The real prize. Live-captioned SRTs repeat the whole visible 2-3 line
# window in every cue, so naive extraction inflates every term's frequency
# 2-3x and skews keyword ranking toward whatever happened to sit mid-window.
# ---------------------------------------------------------------------------


class TestRollingWindowMerge:
    def test_overlapping_window_collapses(self):
        caps = [
            cts.Caption(0, ">> The governor spoke today"),
            cts.Caption(2000, ">> The governor spoke today about the state budget"),
            cts.Caption(4000, "about the state budget and the shortfall ahead"),
        ]
        assert cts.merge_captions(caps) == (
            ">> The governor spoke today about the state budget and the shortfall ahead"
        )

    def test_non_overlapping_cues_are_all_kept(self):
        caps = [cts.Caption(0, "Hello there"), cts.Caption(2000, "Something else entirely")]
        assert cts.merge_captions(caps) == "Hello there Something else entirely"

    def test_exact_repeat_collapses_to_one(self):
        caps = [cts.Caption(0, "same words"), cts.Caption(2000, "same words")]
        assert cts.merge_captions(caps) == "same words"

    def test_overlap_matches_on_word_boundaries_only(self):
        # "budge" must not be treated as an overlap with "budget".
        caps = [cts.Caption(0, "the budge"), cts.Caption(2000, "budget hearing")]
        assert cts.merge_captions(caps) == "the budge budget hearing"

    def test_partial_word_repetition_within_window(self):
        caps = [
            cts.Caption(0, "line one\nline two"),
            cts.Caption(2000, "line two\nline three"),
        ]
        assert cts.merge_captions(caps) == "line one line two line three"


# ---------------------------------------------------------------------------
# End-to-end extraction
# ---------------------------------------------------------------------------


class TestExtract:
    def test_srt_end_to_end(self):
        srt = "1\n00:00:01,000 --> 00:01:03,000\nWisconsin dairy farms\n"
        result = cts.extract(srt)
        assert result.format == "srt"
        assert "Wisconsin dairy farms" in result.text
        assert result.duration_ms == 63_000
        assert result.cue_count == 1

    def test_live_captioning_is_flagged(self):
        # analyst.md keys speaker-change '>>' as the live-caption tell; the
        # skill needs that signal to suppress name-guessing.
        srt = "1\n00:00:01,000 --> 00:00:03,000\n>> Welcome back\n\n2\n00:00:04,000 --> 00:00:06,000\n>> Thanks for having me\n"
        assert cts.extract(srt).live_captioning is True

    def test_post_production_captions_not_flagged(self):
        srt = "1\n00:00:01,000 --> 00:00:03,000\nWelcome back to the show\n"
        assert cts.extract(srt).live_captioning is False

    def test_scc_end_to_end(self):
        scc = "Scenarist_SCC V1.0\n\n" "00:00:01;00\t9420 9420 9470 9470 c8e5 ecec ef2c 20f7 ef72 ec64 2e80 942f 942f\n"
        result = cts.extract(scc)
        assert result.format == "scc"
        assert result.text == "Hello, world."
